# Generated by Django 4.2.17 on 2024-12-26 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(choices=[('Python', 'پایتون'), ('Djangooooooooo', 'جنگو'), ('javaaaaaaa', 'جاوا')], max_length=200),
        ),
    ]
