# Generated by Django 4.2.17 on 2024-12-26 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 7, 1, 57, 799517, tzinfo=datetime.timezone.utc)),
        ),
    ]
