# Generated by Django 4.2.17 on 2024-12-26 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 7, 4, 54, 588820, tzinfo=datetime.timezone.utc)),
        ),
    ]
