# Generated by Django 4.2.17 on 2024-12-29 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 13, 11, 3, 393564, tzinfo=datetime.timezone.utc)),
        ),
    ]
