# Generated by Django 4.2.17 on 2024-12-29 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 29, 13, 48, 26, 117100, tzinfo=datetime.timezone.utc)),
        ),
    ]
