# Generated by Django 4.2.17 on 2025-01-02 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_new_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 5, 47, 9, 39764, tzinfo=datetime.timezone.utc)),
        ),
    ]
