# Generated by Django 5.1.4 on 2025-01-02 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_new_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 2, 30, 59, 704118, tzinfo=datetime.timezone.utc)),
        ),
    ]
