# Generated by Django 4.2.17 on 2025-01-05 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_article_published_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 12, 58, 35, 662318, tzinfo=datetime.timezone.utc)),
        ),
    ]
