# Generated by Django 4.2.17 on 2025-01-05 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_article_slug_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 13, 21, 44, 219908, tzinfo=datetime.timezone.utc)),
        ),
    ]
