# Generated by Django 4.2.17 on 2025-01-23 06:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_article_pub_date_alter_message_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='date',
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 23, 6, 57, 6, 846679, tzinfo=datetime.timezone.utc)),
        ),
    ]
